### ISSUE TITLE
Crash when analyzing dependencies

### ISSUE THREAD

**Issue by james-rabbit** [nknapp/analyze-module-size#6]
`analyze-module-size` crashes when analyzing my project.
The list of dependencies in the error here seems to be from one of the things I depend on, it is not my project's list of dependencies.
Any ideas of what to look for? Can this program ignore the error and continue?

```
Connecting dependency graph
Error: Could not find "/protobufjs" in ["/","/abbrev","/ajv","/ansi-regex","/aproba","/are-we-there-yet","/asn1","/assert-plus","/asynckit","/aws-sign2","/aws4","/balanced-match","/bcrypt-pbkdf","/block-stream","/boom","/brace-expansion","/caseless","/co","/code-point-at","/combined-stream","/concat-map","/console-control-strings","/core-util-is","/cryptiles","/dashdash/assert-plus","/dashdash","/debug","/deep-extend","/delayed-stream","/delegates","/detect-libc","/ecc-jsbn","/extend","/extsprintf","/forever-agent","/form-data","/fs.realpath","/fstream-ignore","/fstream","/gauge","/getpass/assert-plus","/getpass","/glob","/graceful-fs","/har-schema","/har-validator","/has-unicode","/hawk","/hoek","/http-signature","/inflight","/inherits","/ini","/is-fullwidth-code-point","/is-typedarray","/isarray","/isstream","/jsbn","/json-schema","/json-stable-stringify","/json-stringify-safe","/jsonify","/jsprim/assert-plus","/jsprim","/mime-db","/mime-types","/minimatch","/minimist","/mkdirp","/ms","/node-pre-gyp","/nopt","/npmlog","/number-is-nan","/oauth-sign","/object-assign","/once","/os-homedir","/os-tmpdir","/osenv","/path-is-absolute","/performance-now","/process-nextick-args","/punycode","/qs","/rc/minimist","/rc","/readable-stream","/request","/rimraf","/safe-buffer","/semver","/set-blocking","/signal-exit","/sntp","/sshpk/assert-plus","/sshpk","/string_decoder","/string-width","/stringstream","/strip-ansi","/strip-json-comments","/tar-pack","/tar","/tough-cookie","/tunnel-agent","/tweetnacl","/uid-number","/util-deprecate","/uuid","/verror/assert-plus","/verror","/wide-align","/wrappy","#USER","#DEV:/"]
    at packageJson._requiredBy.forEach (/Users/james/.nvm/versions/node/v6.10.3/lib/node_modules/analyze-module-size/src/Package.js:43:17)
    at Array.forEach (native)
    at Package.connect (/Users/james/.nvm/versions/node/v6.10.3/lib/node_modules/analyze-module-size/src/Package.js:40:36)
    at flatPackages.forEach (/Users/james/.nvm/versions/node/v6.10.3/lib/node_modules/analyze-module-size/src/Package.js:113:39)
    at Array.forEach (native)
    at Function.connectAll (/Users/james/.nvm/versions/node/v6.10.3/lib/node_modules/analyze-module-size/src/Package.js:113:18)
    at /Users/james/.nvm/versions/node/v6.10.3/lib/node_modules/analyze-module-size/src/DependencyTree.js:63:41
```

**Comment by nknapp** [comment]
I would try and look where protobufjs is supposed to come from.  If it is not in the dependency-tree, the analyzer will fail. Try cloning the module into a fresh folder, run `npm install` there and then run the analyzer again.

**Comment by nknapp** [comment]
At the moment, the program cannot ignore the error.

**Comment by james-rabbit** [comment]
I removed my dependency on `firebase-admin` and this issue went away. I'm not sure why it was having a problem.
I'm running into a new issue that I will try to debug and may open a new issue.

**Comment by nknapp** [comment]
I'll close this. It seems to be resolved
